GET http://localhost:3000/customers

###

POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Assami Muzaki",
    "item":"Deskmat"
}

###

GET http://localhost:3000/customers/62fb1312ed957f9b084bc3f0

###

DELETE http://localhost:3000/customers/62fb1312ed957f9b084bc3f0

###

PATCH http://localhost:3000/customers/62fb1312ed957f9b084bc3f0
Content-Type: application/json

{
    "name": "Assami Projoi",
    "item":"Demot"
}